---
title: "Stats_C183_HW_3_Charles_Liu"
author: "Charles Liu (304804942)"
date: "5/10/2020"
output: pdf_document
---

# Loading Necessary Packages:
```{r}
library(readr)
```



# 1)
```{r}
# Loading the data for (2012 - 2017) & (2017 - 2020):
a1 <- read.csv("C:/Users/cliuk/Documents/UCLA Works/UCLA Spring 2020/Stats C183/Project/stockData_2012-2017.csv", sep=",", header=TRUE)
a2 <- read.csv("C:/Users/cliuk/Documents/UCLA Works/UCLA Spring 2020/Stats C183/Project/stockData_2017-2020.csv", sep=",", header=TRUE)

# Convert adjusted close prices into returns:
r1 <- (a1[-1,3:ncol(a1)]-a1[-nrow(a1),3:ncol(a1)])/a1[-nrow(a1),3:ncol(a1)]
r2 <- (a2[-1,3:ncol(a2)]-a2[-nrow(a2),3:ncol(a2)])/a2[-nrow(a2),3:ncol(a2)]

# Compute the variance covariance matrix of the returns for each period:
covmat1 <- var(r1)
covmat2 <- var(r2)

# Compute the betas in each period:
beta1 <- covmat1[1,-1] / covmat1[1,1]
beta2 <- covmat2[1,-1] / covmat2[1,1]

# Vasicek's Technique for PRESS:
beta <- rep(0,30)
alpha <- rep(0,30)
sigma_e2 <- rep(0,30)
var_beta <- rep(0,30)

for(i in 1:30){
q2 <- lm(data = r1, formula = r1[,i+1] ~ r1[,1])
beta[i] <- q2$coefficients[2]
alpha[i] <- q2$coefficients[1]
sigma_e2[i] <- summary(q2)$sigma^2
var_beta[i] <- vcov(q2)[2,2]
}

beta2adj_vasicek <- var_beta*mean(beta)/(var(beta) + var_beta) + var(beta)*beta/(var(beta) + var_beta)
names(beta2adj_vasicek) <- names(r1[-1])

PRESS_Vasicek <- sum((beta2adj_vasicek - beta2)^2) / 30

# PRESS Bias:
q <- lm(beta2 ~ beta2adj_vasicek)
SP2 <- sum((beta2adj_vasicek - mean(beta2adj_vasicek))^2) / 30
SA2 <- sum((beta2 - mean(beta2))^2) / 30
PRESS_Bias <- (mean(beta2) - mean(beta2adj_vasicek))^2

# PRESS Inefficiency:
PRESS_Inefficiency <- (1 - q$coefficients[2])^2 * (29/30) * var(beta2adj_vasicek)
attributes(PRESS_Inefficiency) <- NULL


# Components of PRESS from Project 4:
PRESS_Vasicek
PRESS_Bias
PRESS_Inefficiency
```



# 2b)
```{r}
# r = [(B_hat1) * sd(B1)]/[sd(B2)]
# B_hat0 = B_bar2 - B_bar1 * B_hat1
# B_hatC = B_hat0 + B_hat1 * B_i1
Beta_hat1 <- ((0.2744995)*(0.5225564))/(1.154281)
Beta_hat0 <- (1.042003) - (1.068617 * Beta_hat1)
Beta_hatC <- Beta_hat0 + Beta_hat1 * (2.5513904)

# Beta Adjusted for Stock C (Blume's Technique):
Beta_hatC
```